playbox:
  - rajalokan.dotfiles
dockerbox:
  - rajalokan.dotfiles
  - bootstrap_docker
keystone:
  - rajalokan.dotfiles
  - bootstrap_openstack
guts:
  - rajalokan.dotfiles
  - bootstrap_openstack
  - bootstrap_guts
vv:
  - rajalokan.dotfiles
osdev:
  - rajalokan.dotfiles
