rajalokan.dotfiles:
  name: rajalokan.dotfiles
  scm: git
  src: https://github.com/rajalokan/dotfiles.git
  version: master
bootstrap_docker:
  name: bootstrap_docker
  scm: git
  src: https://github.com/rajalokan/ansible_role_bootstrap_docker.git
  version: master
