---

- name: add the server to ansible inventory
  add_host:
    hostname: "{{ SERVER_IP }}"
    groups: "{{ instance_name }}"
    ansible_ssh_private_key_file: "{{ PRIVATE_KEY_FILE }}"
    ansible_ssh_user: ubuntu
