---
- name: "localhost: Setting up instance with following details. name= {{ instance_name }}"
  hosts: localhost
  pre_tasks:
    - block:
      - include_vars: vars/default.yml
      - include_vars: vars/default_vault.yml
      - include_vars: vars/{{ instance_name }}.yml
        ignore_errors: true
      - include_vars: vars/{{ instance_name }}_vault.yml
        ignore_errors: true
      tags: boot
  tasks:
    - block:
      - include: launch_or_get_instance.yml
      - include: wait_for_ssh.yml
      - include: readd_to_known_hosts.yml
      - include: add_to_inventory.yml
      tags: boot

- include: verify_accessibility.yml
  tags: always

- include: "{{ instance_name }}.yml"
  tags: always
