---

- block:
    - name: "Launching instance: {{ instance_name }} with floating ip {{ FLOATING_IP }}"
      os_server:
        name: "{{ instance_name }}"
        state: present
        wait: yes
        image: "{{ IMAGE }}"
        endpoint_type: "internal"
        flavor: "{{ FLAVOR }}"
        key_name: "{{ KEY_NAME }}"
        network: "{{ NETWORK }}"
        floating_ips:
          - "{{ FLOATING_IP }}"
      register: server

    - name: Launched instance public IP
      debug:
        var: server.server.public_v4
  when: FLOATING_IP is defined

- block:
    - name: "Launching instance: {{ instance_name }} with private IP in network {{ NETWORK }} for {{ IMAGE }} image and {{ FLAVOR }} flavor and {{ KEY_NAME}}"
      os_server:
        name: "{{ instance_name }}"
        state: present
        wait: yes
        image: "{{ IMAGE }}"
        endpoint_type: "internal"
        flavor: "{{ FLAVOR }}"
        key_name: "{{ KEY_NAME }}"
        network: "{{ NETWORK }}"
      register: server

    # - name: Launched instance public IP
    #   debug:
    #     var: server.server
  when: FLOATING_IP is not defined
