---

# Run playbooks
- name: "ney11: Running roles: dotfiles"
  hosts: ney11
  roles:
    - { role: ansible_role_dotfiles }
  tasks:
    - name: Make opt owned by user
      file:
        path: /opt
        owner: "ubuntu"
      become: true

    - name: Clone cloud--installer
      git:
        repo: https://github.com/rajalokan/cloud-installer.git
        dest: /opt/cloud--installer
