---

# Run playbooks
- name: "GUTS : Run roles & tasks for setting up `guts`"
  hosts: guts_all
  roles:
    # - { role: rajalokan.dotfiles }
    # - { role: bootstrap_openstack }
    - { role: bootstrap_guts }
  vars:
    mysql_root_password: rajalokan
    guts_db_password: rajalokan
